### ISSUE TITLE
help

### ISSUE THREAD

**Issue by H6PSRjmuIeu7mSRxhQI5** [flowxrc/csgo-xenforo-loader#3]
how to find client id and secret id

![image](https://user-images.githubusercontent.com/66646239/186520860-9175eb5c-e6b6-42bc-bc48-3f3c36ce06ca.png)
  secretid = xenforo api or?
  clientid?

**Comment by yarz9** [comment]
wondering too

**Comment by dgrachov** [comment]
Sorry for the slow response, no, this is not xenforo, it is a key passed over to server just a safety check, not a really good one but it's there. You have to change client and secret key in globals.hpp in your loader project to match the ones you have on server
